server:  
  servlet:
    contextPath: /api/v1

logging:
  level:
    root: INFO
      
springfox:
  documentation: 
    swagger: 
      v2:
        path: /api-docs    
    
spring:  
  data:
    rest:
      defaultMediaType: application/json
  hateoas:
    use-hal-as-default-json-media-type: false
  jpa:
    hibernate:
      ddl-auto: none
    database: POSTGRESQL
    show-sql: 'true'
  datasource:
    plataform: postgres
    url: jdbc:postgresql://localhost:5432/poc
    username: postgres
    password: root
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

keycloak:
  ssl-required: external
  realm: poc
  resource: poc-api
  auth-server-url: http://localhost:8180/auth/
  credentials:
    secret: 64338a09-004d-42ec-96b9-14d82be472dc
  use-resource-role-mappings: true
  security-constraints:
    - authRoles:
        - ROLE_POC_CONSULTAR_EMPRESA
      securityCollections:
        - name: Consultar empresas
          patterns: /empresas/*
          methods: GET
    - authRoles:
        - ROLE_POC_CRIAR_EMPRESA
      securityCollections:
        - name: Criar empresas
          patterns: /empresas/*
          methods: POST
    - authRoles:
        - ROLE_POC_ATUALIZAR_EMPRESA
      securityCollections:
        - name: Atualizar empresas
          patterns: /empresas/*
          methods: PUT
    - authRoles:
        - ROLE_POC_DELETAR_EMPRESA
      securityCollections:
        - name: Deletar empresas
          patterns: /empresas/*
          methods: DELETE